name: timesheet
publish_to: 'none'
version: 0.0.0-semantically-released

environment:
  sdk: ^3.11.0
flutter:
  assets:
    - assets/config.json
    - assets/logo.png
flutter_launcher_icons:
  macos:
    generate: true
    image_path: assets/icon.png

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.8.1
  macos_ui: ^2.2.0
  cupertino_calendar_picker: ^2.2.6
  provider: ^6.1.5+1
  openid_client: ^0.4.9
  url_launcher: ^6.3.2
  path: ^1.9.1
  logging: ^1.3.0
  sqflite_common_ffi: ^2.3.6
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  test: ^1.26.2
  flutter_launcher_icons: ^0.14.4
